jobs:

- job:
  strategy:
    matrix:
      Mojave-Xcode-10.2.1:
        IMAGE_POOL: 'macOS-10.14'
        XCODE_VERSION: '10.2.1'
      Mojave-Xcode-11.0:
        IMAGE_POOL: 'macOS-10.14'
        XCODE_VERSION: '11'
  pool:
    vmImage: $(IMAGE_POOL)
  
  steps:

  - script: sudo xcode-select --switch "/Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer"
    displayName: "Select Xcode $(XCODE_VERSION)"
  
  - script: |
      set -e
      git clone https://$(GitHubAccessToken)@github.com/xamarinhq/calabash-codesign.git
      calabash-codesign/apple/create-keychain.sh
    displayName: "Download and install keychain"

  - script: make app-agent
    displayName: "Make app-agent"

  - script: make ipa-agent
    displayName: "Make ipa-agent"
  
  - script: make test-ipa
    displayName: "Make test-ipa"

  - script: make test-app
    displayName: "Make test-app"

  - script: bundle install
    displayName: "Bundle install"

  - script: |
      cd cucumber 
      bundle install
    displayName: "cd cucumber and bundle install"

  - script: make unit-tests
    displayName: "Make unit-tests"

  - script: bundle exec bin/ci/cucumber.rb
    displayName: "exec cucmber"

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFiles: 'cucumber/reports/junit/*.xml'
      failTaskOnFailedTests: true
    condition: always()